services:
  spiffworkflow-frontend:
    container_name: spiffworkflow-frontend
    image: ghcr.io/sartography/spiffworkflow-frontend:latest
    environment:
      APPLICATION_ROOT: "/"
      PORT0: "${SPIFFWORKFLOW_FRONTEND_PORT:-8001}"
    ports:
      - "${SPIFFWORKFLOW_FRONTEND_PORT:-8001}:${SPIFFWORKFLOW_FRONTEND_PORT:-8001}/tcp"
  
  db:
    container_name: db
    image: mysql:8.0.29
    environment:
      - MYSQL_DATABASE=${SPIFFWORKFLOW_BACKEND_DATABASE_NAME:-spiffworkflow_backend_development}
      - MYSQL_ROOT_PASSWORD=${SPIFFWORKFLOW_BACKEND_MYSQL_ROOT_DATABASE:-my-secret-pw}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  rmq:
    image: registry.it-serv.dev/hub.docker.com/library/rabbitmq:3.11.7-management
    environment:
      - TZ=${TZ}
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=default
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: registry.it-serv.dev/hub.docker.com/library/redis:7.0.8
    environment:
      - TZ=${TZ}
    ports:
      - '6379:6379'
    command:
      - "redis-server"
      - "--requirepass"
      - "admin"

  
  # spiffworkflow-backend:
  #   container_name: spiffworkflow-backend
  #   image: ghcr.io/sartography/spiffworkflow-backend:latest
  #   # Enable setting the ownership of created files to match the local user:group. For example:
  #   #     RUN_AS="$(id -u):$(id -g)" docker compose up -d
  #   user: ${RUN_AS:-0:0}
  #   depends_on:
  #     db:
  #       condition: service_started
  #   environment:
  #     FLASK_DEBUG: "0"
  #     SPIFF_BACKEND_PORT : 8000
  #     SPIFFWORKFLOW_BACKEND_CONNECTOR_PROXY_URL : "http://127.0.0.1:7004/"

  #     SPIFFWORKFLOW_BACKEND_ENV: "local_docker"
  #     FLASK_SESSION_SECRET_KEY : ${FLASK_SESSION_SECRET_KEY:-e7711a3ba96c46c68e084a86952de16f}

  #     SPIFFWORKFLOW_BACKEND_URL: "http://localhost:${SPIFF_BACKEND_PORT:-8000}"

  #     SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR : "./process_models"

  #     SPIFFWORKFLOW_BACKEND_DATABASE_URI: "mysql+mysqldb://root:${SPIFFWORKFLOW_BACKEND_MYSQL_ROOT_DATABASE:-my-secret-pw}@db:3306/${SPIFFWORKFLOW_BACKEND_DATABASE_NAME:-spiffworkflow_backend_development}"


  #     SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA: "false"
  #     SPIFFWORKFLOW_BACKEND_LOG_LEVEL: "DEBUG"
  #     SPIFFWORKFLOW_BACKEND_OPEN_ID_CLIENT_ID: "spiffworkflow-backend"
  #     SPIFFWORKFLOW_BACKEND_OPEN_ID_CLIENT_SECRET_KEY: "my_open_id_secret_key"
  #     SPIFFWORKFLOW_BACKEND_OPEN_ID_SERVER_URL: "http://localhost:${SPIFF_BACKEND_PORT:-8000}/openid"
  #     SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME: "example.yml"
  #     SPIFFWORKFLOW_BACKEND_PORT: "${SPIFF_BACKEND_PORT:-8000}"
  #     SPIFFWORKFLOW_BACKEND_RUN_BACKGROUND_SCHEDULER_IN_CREATE_APP: "true"
  #     SPIFFWORKFLOW_BACKEND_UPGRADE_DB: "true"
  #     SPIFFWORKFLOW_BACKEND_URL_FOR_FRONTEND: "http://localhost:${SPIFFWORKFLOW_FRONTEND_PORT:-8001}"
  #   ports:
  #     - "${SPIFF_BACKEND_PORT:-8000}:${SPIFF_BACKEND_PORT:-8000}/tcp"
  #   volumes:
  #     - ${SPIFFWORKFLOW_BACKEND_LOCAL_BPMN_SPEC_DIR:-./process_models}:/app/process_models
  #   healthcheck:
  #     test: "curl localhost:${SPIFF_BACKEND_PORT:-8000}/v1.0/status --fail"
  #     interval: 10s
  #     timeout: 5s
  #     retries: 20


volumes:
  db:
