

kill -9 $(lsof -t -i :8000)

export FLASK_DEBUG=0
export FLASK_SESSION_SECRET_KEY=${FLASK_SESSION_SECRET_KEY:-e7711a3ba96c46c68e084a86952de16f}
export SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR="./process_models"
export SPIFFWORKFLOW_BACKEND_DATABASE_URI="mysql+mysqldb://root:${SPIFFWORKFLOW_BACKEND_MYSQL_ROOT_DATABASE:-my-secret-pw}@127.0.0.1:3306/${SPIFFWORKFLOW_BACKEND_DATABASE_NAME:-spiffworkflow_backend_development}"
export SPIFFWORKFLOW_BACKEND_ENV=${SPIFFWORKFLOW_BACKEND_ENV:-local_development}
export SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA=${SPIFFWORKFLOW_BACKEND_LOAD_FIXTURE_DATA:-false}
export SPIFFWORKFLOW_BACKEND_OPEN_ID_SERVER_URL=${SPIFFWORKFLOW_BACKEND_OPEN_ID_SERVER_URL:-http://localhost:8000/realms/spiffworkflow-local}
export SPIFFWORKFLOW_BACKEND_PERMISSIONS_FILE_NAME="local_development.yml"
export SPIFFWORKFLOW_BACKEND_PORT=8000
export SPIFFWORKFLOW_BACKEND_RUN_BACKGROUND_SCHEDULER_IN_CREATE_APP="false"
export SPIFFWORKFLOW_BACKEND_URL_FOR_FRONTEND="http://localhost:8001"
export SPIFFWORKFLOW_BACKEND_UPGRADE_DB=true
export SPIFFWORKFLOW_BACKEND_URL="http://localhost:8000"
export SPIFFWORKFLOW_BACKEND_LOG_LEVEL="debug"
export SPIFFWORKFLOW_BACKEND_GIT_PUBLISH_CLONE_URL="https://github.com/sartography/sample-process-models.git"
export SPIFFWORKFLOW_BACKEND_GIT_USERNAME="sartography-automated-committer"
export SPIFFWORKFLOW_BACKEND_GIT_USER_EMAIL="sartography-automated-committer@users.noreply.github.com"
export SPIFFWORKFLOW_BACKEND_EXTENSIONS_API_ENABLED="true"
export SPIFFWORKFLOW_BACKEND_GIT_SOURCE_BRANCH="sample-models-1"
export SPIFFWORKFLOW_BACKEND_CONNECTOR_PROXY_URL : "http://127.0.0.1:7004/"

./bin/run_server_locally